# Generated by Django 5.1.6 on 2025-03-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionpoint',
            old_name='adress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='subscribable',
            field=models.BooleanField(default=False),
        ),
    ]
