# Generated by Django 5.1.6 on 2025-03-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_adress_collectionpoint_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionpoint',
            old_name='subscribable',
            new_name='public',
        ),
        migrations.RemoveField(
            model_name='collectionpoint',
            name='name',
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='capacity',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='horaires',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='collection_points/'),
        ),
    ]
