# Generated by Django 5.1.6 on 2025-03-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_subscribable_collectionpoint_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='horaires',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
