# Generated by Django 5.1.6 on 2025-03-08 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_collectionpoint_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpoint',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_points', through='core.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
