# Generated by Django 5.1.6 on 2025-03-08 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_collectionpoint_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionpoint',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='collectionpoint',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
