# Generated by Django 5.1.6 on 2025-03-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_collectionpoint_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
