# Generated by Django 5.1.6 on 2025-03-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_collectionpoint_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpoint',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
