# Generated by Django 5.1.6 on 2025-03-10 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_collectionpoint_created_at_and_more'),
        ('users', '0005_alter_user_address_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='composters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composters', to='core.collectionpoint'),
        ),
    ]
