# Generated by Django 5.1.6 on 2025-03-10 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_composters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='composters',
        ),
    ]
