# Generated by Django 5.1.6 on 2025-03-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_collectionpoint_id_alter_subscription_id'),
        ('users', '0008_user_owned_composters_user_subscribed_composters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='owned_composters',
            field=models.ManyToManyField(default=[], related_name='owned_composters', to='core.collectionpoint'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribed_composters',
            field=models.ManyToManyField(default=[], related_name='subscribed_composters', to='core.collectionpoint'),
        ),
    ]
